version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fake_provider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8898:8888"
    depends_on:
      - postgres