@startuml

actor Client

participant "Individuals API" as IA
participant "Transaction Service" as TS
participant "Payment Service" as PS
participant "Fake Payment Provider" as FP

== Получение методов оплаты ==

Client -> IA : Запрос методов оплаты

IA -> PS : GET /payment-methods/{currency}/{country}

PS -> PS : Поиск методов оплаты в БД

PS --> IA : Список методов + required fields

IA --> Client : Список методов оплаты

== Создание платежа ==

Client -> IA : Создать платеж

note right
Пользователь уже выбрал
метод оплаты и заполнил поля
карты/QR/прочее
end note

IA -> TS : Создать транзакцию

TS --> IA : transactionUid (PENDING)

IA -> PS : POST /payments

PS -> PS : Валидация данных

PS -> PS : Сохранить Payment(PENDING)

PS -> FP : Провести платеж

alt Успех

FP --> PS : providerTransactionId

PS -> PS : Payment(COMPLETED)

PS --> IA : SUCCESS + providerTransactionId

IA -> TS : Обновить транзакцию

TS -> TS : status=COMPLETED

TS -> TS : save providerTransactionId

TS --> IA : OK

IA --> Client : Платеж успешен

else Ошибка провайдера

FP --> PS : ERROR

PS -> PS : Payment(FAILED)

PS --> IA : FAILED

IA -> TS : Компенсация

TS -> TS : status=FAILED

TS --> IA : OK

IA --> Client : Ошибка платежа

end

@enduml