@startuml

skinparam componentStyle rectangle

package "Currency Rate Service" {

  package "API Layer" {
      [CurrencyRateController]
  }

  package "Scheduler Layer" {
      [RateUpdateScheduler]
  }

  package "Business Logic Layer" {
      [ExchangeRateService]
  }

  package "Integration Layer" {
      [ExternalRateProviderClient]
  }

  package "Persistence Layer" {
      [CurrencyRepository]
      [ConversionRateRepository]
      [RateProviderRepository]
  }

}

database "PostgreSQL"

[CurrencyRateController] --> [ExchangeRateService] : получить курс

[RateUpdateScheduler] --> [ExchangeRateService] : updateRates()

[ExchangeRateService] --> [ExternalRateProviderClient] : запрос курсов

[ExchangeRateService] --> [CurrencyRepository] : получить валюты

[ExchangeRateService] --> [ConversionRateRepository] : сохранить курсы

[ExchangeRateService] --> [RateProviderRepository] : получить провайдера

[CurrencyRepository] --> "PostgreSQL"

[ConversionRateRepository] --> "PostgreSQL"

[RateProviderRepository] --> "PostgreSQL"

@enduml