spring:
  application:
    name: currencyRateService
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_rate_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8083
  servlet:
    context-path: /api/v1


cbr:
  url: https://www.cbr.ru