version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: transaction_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d transaction_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:10
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/transaction_db -user=app_user -password=app_password -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
