spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081


