spring:
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Настройки Envers для аудита
        envers:
          audit_table_suffix: _AUDIT
          store_data_at_delete: true
  main:
    allow-circular-references: true

# Настройки OpenAPI генерации
openapi:
  spec-path: classpath:openapi/person-service.yml
  generated-package: com.artem.api

# Настройки безопасности API Key
api:
  security:
    key: SECRET_API_KEY_FOR_INTER_SERVICE_COMM

# Настройки логирования
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.artem: DEBUG


server:
  port: 8081
  servlet:
    context-path: /api


