#spring:
#  application:
#    name: person-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/person
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        # Общие настройки Hibernate
#      # Настройки для Spring Data Envers
#      org.hibernate.envers.audit_table_suffix: _AUDIT
#      org.hibernate.envers.store_data_at_delete: true
#  main:
#    allow-circular-references: true
#  data:
#    envers:
#      # Дополнительные настройки Spring Data Envers
#      revision-datetime-utc: true
#
## Остальные настройки без изменений
#openapi:
#  spec-path: classpath:openapi/person-service.yml
#  generated-package: com.artem.api
#
#api:
#  security:
#    key: SECRET_API_KEY_FOR_INTER_SERVICE_COMM
#
#logging:
#  level:
#    root: INFO
#    org.springframework: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    com.artem: DEBUG
#    org.springframework.data.envers: DEBUG # Логирование для Spring Data Envers
#
#server:
#  port: 8081
#  servlet:
#    context-path: /api
#
spring:
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: person
        # Дополнительные настройки
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Правильное расположение
  main:
    allow-circular-references: true
  data:
    envers:
      revision-datetime-utc: true

# Настройки для Envers
org:
  hibernate:
    envers:
      audit_table_suffix: _AUDIT
      store_data_at_delete: true

openapi:
  spec-path: classpath:openapi/person-service.yml
  generated-package: com.artem.api

api:
  security:
    key: SECRET_API_KEY_FOR_INTER_SERVICE_COMM

logging:
  level:
    root: INFO
    com.artem.person service.service: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.artem: DEBUG
    org.springframework.data.envers: DEBUG

server:
  port: 8091
#  servlet:
#    context-path: /api